version: 2.1
jobs:
  build:
    docker:
      - image: ruby:3.3.0
    steps:
      - checkout
      - run:
          name: Run the default task
          command: |
            gem install bundler -v 2.5.11
            bundle install
            bundle exec rake
