#!/usr/bin/env ruby
# frozen_string_literal: true

require "bundler/setup"
require "omniai/mistral"

CLIENT = OmniAI::Mistral::Client.new

TOOL = OmniAI::Tool.new(
  proc { |location:, unit: "celsius"| "#{rand(20..50)}° #{unit} in #{location}" },
  name: "Weather",
  description: "Lookup the weather in a location",
  parameters: OmniAI::Tool::Parameters.new(
    properties: {
      location: OmniAI::Tool::Property.string(description: "e.g. Toronto"),
      unit: OmniAI::Tool::Property.string(enum: %w[celcius farenheit]),
    },
    required: %i[location]
  )
)

puts "> [SYSTEM] You are an expert in weather."
puts "> [USER] What is the weather in 'London' in celsius and 'Madrid' in fahrenheit?"

CLIENT.chat(stream: $stdout, tools: [TOOL]) do |prompt|
  prompt.system "You are an expert in weather."
  prompt.user 'What is the weather in "London" in celsius and "Madrid" in fahrenheit?'
end
